name: release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    # This only works on "run" commands
    defaults:
      run:
        working-directory: ./app/human-detector-app
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v3

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: ğŸ— Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¦ Install dependencies
        run: npm install
        
      - name: ğŸ— Setup EAS Local builds
        run: npm install -g eas-cli-local-build-plugin

      - name: ğŸš€ Build app
        run: |
          eas build --local \
          --platform=android \
          --profile=production \
          --output=./app-build \
          --non-interactive
          
      - name: List eas output
        run: ls -a ./app-build
        
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'release' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./app/human-detector-app/*.apk
          tag: ${{ github.ref }}
