name: release

# Need write permission to release
permissions:
  contents: write

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  trigger_pi_build:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PI_GEN_PAT }}
        repository: eyespy-cam/pi-gen
        event-type: eyespy-release
        client-payload: '{"eyespy_tag": "${{ github.ref_name }}"}'
        
  build:
    env:
      GH_TOKEN: ${{ github.token }}
      BACKEND_URL: ${{ secrets.BACKEND_URL }}
      OIDC_ENDPOINT: ${{ secrets.OIDC_ENDPOINT }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      GOOGLE_SERVICES_JSON: "./google_services.json"
      
    # This only works on "run" commands
    defaults:
      run:
        working-directory: ./app/human-detector-app
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ— Setup repo
        uses: actions/checkout@v3

      - name: ðŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: ðŸ— Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ðŸ“¦ Install dependencies
        run: npm install
        
      - name: ðŸ— Setup EAS Local builds
        run: npm install -g eas-cli-local-build-plugin

      - name: Write secrets
        run: 'echo "$GOOGLE_JSON" > ./google_services.json'
        shell: bash
        env:
          GOOGLE_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
  
      - name: ðŸš€ Build app
        run: |
          eas build --local \
          --platform=android \
          --profile=production \
          --output=human-detector-app.apk \
          --non-interactive
          
      - name: List eas output
        run: file human-detector-app.apk
        
      - name: Upload binaries to release
        run: gh release upload ${{ github.ref_name }} human-detector-app.apk
        if: ${{ github.event_name == 'release' }}
